version: '3'
services:
  php:
    image: php:7.4-fpm
    container_name: practicephp
    volumes:
      - ./php-practice:/var/www/html
    networks:
      - mynetwork
  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./php-practice:/var/www/html
    depends_on:
      - php
    networks:
      - mynetwork
networks:
  mynetwork: