version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - mynetwork
  php-fpm:
    image: php:8-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - mynetwork
  mysql:
    image: mysql:5.7.43
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Replace with your desired password
      MYSQL_DATABASE: myapp
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Map container port 3306 to host port 3306
volumes:
  mysql_data:
networks:
  mynetwork: