version: '3'
services:
  mariadb:
    image: mariadb:10.5.8
    container_name: maria
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

