version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
    networks:
      - mynetwork
  php:
    build: .
    container_name: php
    volumes:
      - ./app:/var/www/html
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
    depends_on:
      - mysql
    networks:
      - mynetwork
  mysql:
    image: mysql:5.7.43
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Replace with your desired password
      MYSQL_DATABASE: myapp
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"  # Map container port 3306 to host port 3306
    networks:
      - mynetwork
volumes:
  mysql_data:
networks:
  mynetwork: